### ISSUE TITLE
[Débito técnico] Rotas com acento estranho (?) / Header triplicado

### ISSUE THREAD

**Issue by lucasinocente** [5minutosde/client#2]
Problemas / Limitações:
- Tá começando a ficar demorado ter que editar vários arquivos index.html
- Limitação de rotas
- Usuário acha estranho rota com ?
- Possível limitação de navegadores com js atual

---

Faz sentido migrar pra algum framework?

**Comment by guilhermecomum** [comment]
Eu voto em usar alguma coisa moda jovem

**Comment by lucasalacerda** [comment]
Que tal usarmos a poderosa lib para front-end "React"?

**Comment by lucasinocente** [comment]
Tá rolando no PR https://github.com/5minutosde/client/pull/3
